version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/component-processing-service-777-task-definition:latest"
        LoadBalancerInfo:
          ContainerName: "component-processing-service-777"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"